### ISSUE TITLE
Research recipe website api

### ISSUE THREAD

**Issue by lukharri** [lukharri/RecipeBlender#1]
https://market.mashape.com/

**Comment by the-pat** [comment]
[market.mashape](https://market.mashape.com) provides many APIs from several companies. The API we looked at earlier is from [spoonacular](https://spoonacular.com/food-api).

Here are several recipe APIs:
- [spoonacular](https://spoonacular.com/food-api)
- [BigOven](http://api2.bigoven.com)
- [Yummly](https://developer.yummly.com/)
- [Food2Fork](https://food2fork.com/about/api)
- [Recipe Puppy](http://www.recipepuppy.com/about/api/)

spoonacular seems looks like a good choice. One down side is the free tier is limited to 50 requests/day.

For calling the API, using a SDK would be the easiest route. But here are some alternatives:
- [stackoverflow](https://stackoverflow.com/a/3916369)
- [OkHttp](https://square.github.io/okhttp/)
- [android-async-http library](https://stackoverflow.com/a/29339731)
- [Apache HttpClient](https://hc.apache.org/httpcomponents-client-4.5.x/index.html)

**Comment by lukharri** [comment]
I found another one here [https://developer.edamam.com/](url). This one allows commercial use for free and also uses Natural Language Processing. That would be a killer feature!

**Comment by lukharri** [comment]
I signed up for a developer account with Edamam and contacted them. They're going to upgrade the account to a starter account for us which has the services I mentioned earlier. Let me know what you think. 

I'm building a project now to test out the API and see what I can do with it.

**Comment by the-pat** [comment]
[Edamam](https://www.edamam.com/) looks really great.

The terms, limits, and pricing look better than the other APIs. Can you put the project in a branch?
